[package]
name = "orderbook_viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
eframe = "0.34.3"
egui = "0.34.3"
egui-file-dialog = "0.13.0"
egui_plot = "0.35.0"
polars = { version = "0.41", features = [
  "lazy",
  "parquet",
  "temporal",
  "rank",
  "dtype-datetime",
  "dtype-categorical",
  "dtype-decimal",
] }
uuid = { version = "1.0", features = ["v4"] }
hashbrown = { version = "0.14.5", features = ["raw"] }
